os: linux
language: node_js
node_js:
  - 'stable'
addons:
  chrome: stable
dist: trusty
install:
  - yarn add codecov
cache:
  directories:
    - node_modules

before_script:
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn test --coverage --watchAll=false
  - yarn build
after_success:
  - codecov
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
