language: node_js
node_js:
  - "stable"
install:
  - yarn add codecov
cache:
  directories:
    - node_modules
script:
  - yarn test --coverage --watchAll=false --coverageReporters=text-lcov
  - codecov -f coverage/*.json
  - yarn build