#codecov:
#  require_ci_to_pass: yes

coverage:
  range: "0...100"
#  precision: 2
#  round: down
#  status:
#    patch:
#      default:
#        enabled: false

#parsers:
#  gcov:
#    branch_detection:
#      conditional: yes
#      loop: yes
#      method: no
#      macro: no

#comment:
#  layout: "reach,diff,flags,tree"
#  behavior: default
#  require_changes: no
